// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlprzthrgzxonunihlau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndscHJ6dGhyZ3p4b251bmlobGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NzEzNjIsImV4cCI6MjA3MjE0NzM2Mn0.KpZJBr6Y9-YIgFtA49lKpAYemDMZ_wM6bvQmI5_Mxcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});